Repository ArshdeepGrover/ai-tools-manager, pull requests merged in 2025-08, with the labels that each got.

#1 feat: transform project into professional AI tools directory
  .github/ISSUE_TEMPLATE/add-new-tool.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/pull_request_template.md
  .gitignore
  COMMIT_GUIDELINES.md
  CONTRIBUTING.md
  CONTRIBUTOR_EXAMPLE.md
  LICENSE
  README.md
  assets/README.md
  assets/favicon.svg
  assets/og-image.svg
  contributors.json
  index.html
  manifest.json
  robots.txt
  script.js
  sitemap.xml
  style.css
Labels: Possible security concern, Review effort 4/5

#3 feat(contributors): enhance contributor profiles with LinkedIn and taglines
  contributors.json
  script.js
Labels: Ready To Review, Tested

#8 refactor(tool): add new tool with new category AI Model Prototyping: Google AI Studio
  contributors.json
  links.json
Labels: Review effort 2/5, Ready To Merge

#9 MERGE REQUEST PRODUCTION
  contributors.json
  links.json
Labels: Review effort 1/5

#10 feat(contributors, links): add Prerna Rawal as contributor and includ…
  contributors.json
  links.json
Labels: Review effort 1/5

#13 MERGE REQUEST PRODUCTION
  contributors.json
  links.json
Labels: Merge Request
