Repository ArshdeepGrover/ai-tools-manager, pull requests merged in 2025-10, with the labels that each got.

#64 Added "Monica" under the AI Writing & Content category
  contributors.json
  links.json
Labels: Ready To Review, Ready To Merge

#67 feat: improve mobile navbar and back-to-top button
  index.html
  script.js
Labels: Ready To Review, Ready To Merge

#68 MERGE REQUEST PRODUCTION
  contributors.json
  index.html
  links.json
  script.js
Labels: Ready To Review, Merge Request, Deployment

#69 docs/ added social links in contributor list
  contributors.json
Labels: Ready To Review

#76 Something like "feat(tools): add Simplified AI Writer to AI Writing & Content category"
  contributors.json
  links.json
Labels: Ready To Review, Ready To Merge

#78 Added Zoho Show's Zia AI
  contributors.json
  links.json
Labels: Ready To Review, Ready To Merge

#79 Fixed the persistent blue outline over the buttons when clicked
  style.css
Labels: Ready To Review, Ready To Merge

#89 add: promptly ai to ai tools collection
  contributors.json
  links.json
Labels: Ready To Review, Ready To Merge, hacktoberfest-accepted

#84 Add scroll show less
  index.html
  script.js
  style.css
Labels: Ready To Review, Ready To Merge, hacktoberfest-accepted

#85 added 2 tools and on some browsers tailwindcss was not working so Fixed that Also
  README.md
  contributors.json
  index.html
  links.json
Labels: Ready To Review, Ready To Merge

#96 fix: contributors grid array (#95)
  README.md
  contributors.json
  index.html
  links.json
  package-lock.json
Labels: Merge Request, Deployment

#98 Merge: fixes, tools added, enhancement
  links.json
Labels: Merge Request, Deployment

#107 changed navbar again
  index.html
  style.css
Labels: bug, Ready To Review, Ready To Merge, hacktoberfest-accepted

#108 fix: navbar mobile responsive
  contributors.json
  index.html
  links.json
  script.js
  style.css
Labels: Ready To Review, Deployment, Ready To Merge, hacktoberfest-accepted

#114 total 6 more tools has been added in 2 category , and updated Contribution
  contributors.json
  links.json
Labels: Ready To Review, Ready To Merge, hacktoberfest-accepted

#116 Feat: add tools and fix design
  contributors.json
  links.json
Labels: Ready To Review, Deployment, Ready To Merge, hacktoberfest-accepted

#119 Update pr-create-automate-message.yml
  .github/workflows/pr-create-automate-message.yml
Labels: documentation, Ready To Review, Ready To Merge, hacktoberfest-accepted

#123 fix(workflows): check duplicate and validate data
  .github/workflows/check-duplicates.yml
  .github/workflows/validate-data.yml
  validate-links.js
Labels: Ready To Review, Ready To Merge, hacktoberfest-accepted

#122 Fixed the ReferenceError in the filterByCategory() function
  script.js
Labels: Ready To Review, Ready To Merge, hacktoberfest-accepted

#121 Add 2 new AI Tools
  contributors.json
  links.json
Labels: Ready To Review, Ready To Merge, hacktoberfest-accepted
